### PR TITLE
Dialog v0.1.0

### PR DESCRIPTION
**Pull request by QuinnWilton**
📙 [Preview](https://github.com/fission-codes/spec/blob/dialog-v0.1.0/dialog/README.md)

### CODE REVIEW

**Comment by expede** [comment]
@QuinnWilton two proposals for you (with XOR semantics)

1. Quickly clean up and merge this to `main` now, and we make small PRs into the WIP specs
1. Treat this PR as the core feature branch, and break off PRs from this one

I have a slight preference for the first one, but also 🤷‍♀️ Thoughts?

**Comment by QuinnWilton** [comment]
> @QuinnWilton two proposals for you (with XOR semantics)
> 
> 1. Quickly clean up and merge this to `main` now, and we make small PRs into the WIP specs
> 2. Treat this PR as the core feature branch, and break off PRs from this one
> 
> I have a slight preference for the first one, but also 🤷‍♀️ Thoughts?

Let's go with the first one! It's all the same to me :)

**Comment by QuinnWilton** [comment]
@expede I just flipped this over from being a draft PR! There's obviously still a lot of work to do, but what's here is mostly correct, if unfinished.

**Review by expede — APPROVED** [review]
Looks great! Ship it 🚀

**Comment by QuinnWilton** [comment]
Awesome! Lemme just setup commit signing then I'll push up and merge

**Pull request merged**
